"use client";
import {useState} from "react";
import {ArrowUpRight,LoaderCircle,CheckCircle2,AlertCircle} from "lucide-react";
import {site} from "@/content/site";
import {trackQuoteSuccess} from "@/components/site/analytics";
type Values={name:string;email:string;phone:string;project:string};
const initial={name:"",email:"",phone:"",project:""};
export function QuoteForm(){
 const[values,setValues]=useState<Values>(initial),[errors,setErrors]=useState<Partial<Values>>({}),[status,setStatus]=useState<"idle"|"sending"|"success"|"error"|"unavailable">("idle");
 const validate=()=>{const e:Partial<Values>={};if(!values.name.trim())e.name="Please enter your name.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email))e.email="Please enter a valid email address.";if(!values.project.trim())e.project="Please tell us a little about your project.";setErrors(e);return Object.keys(e).length===0};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!validate()){setStatus("idle");requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('[aria-invalid="true"]')?.focus());return}if(!site.quoteEndpoint){setStatus("unavailable");return}
 setStatus("sending");try{const response=await fetch(site.quoteEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error("Request failed");const result=await response.json();if(!result || typeof result!=="object" || !("success" in result) || result.success!==true)throw new Error("Not accepted");setStatus("success");setValues(initial);trackQuoteSuccess()}catch{setStatus("error")}}
 return <form className="quote-form" id="quote-form" onSubmit={submit} noValidate><p className="form-heading">Tell us what you have in mind.</p><p className="form-hint">Fields marked * are required.</p><div className="form-grid">{(["name","email","phone"] as const).map(k=><div className={"field "+(k==="phone"?"full":"")} key={k}><label htmlFor={k}>{k[0].toUpperCase()+k.slice(1)} {k!=="phone"?"*":"(optional)"}</label><input id={k} name={k} type={k==="email"?"email":k==="phone"?"tel":"text"} autoComplete={k==="phone"?"tel":k} maxLength={k==="name"?120:k==="email"?254:40} required={k!=="phone"} value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})} aria-invalid={!!errors[k]} aria-describedby={errors[k]?k+"-error":undefined} placeholder={k==="name"?"Your name":k==="email"?"Your email address":"Your phone number"}/>{errors[k]&&<p id={k+"-error"} className="field-error">{errors[k]}</p>}</div>)}<div className="field full"><label htmlFor="project">Tell us about your project *</label><textarea id="project" name="project" maxLength={5000} rows={4} required value={values.project} onChange={e=>setValues({...values,project:e.target.value})} placeholder="What would you like to build or improve?" aria-invalid={!!errors.project} aria-describedby={errors.project?"project-error":undefined}/>{errors.project&&<p id="project-error" className="field-error">{errors.project}</p>}</div></div>
 <button className="button" type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Request a quote"}{status==="sending"?<LoaderCircle className="spinner" size={18}/>:<ArrowUpRight size={18}/>}</button><div role="status" aria-live="polite" className={"form-status "+status}>{status==="success"&&<><CheckCircle2 size={20}/>Your request has been sent successfully. We’ll be in touch soon.</>}{status==="error"&&<><AlertCircle size={20}/>We couldn’t send your request. Your details are still here; please try again or call +1 (773) 726-7560.</>}{status==="unavailable"&&<><AlertCircle size={20}/>Online quote requests are temporarily unavailable. Call +1 (773) 726-7560 to request a quote.</>}</div></form>
}
